apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resourceservers.kubernetes.auth0.com
spec:
  group: kubernetes.auth0.com
  names:
    kind: ResourceServer
    listKind: ResourceServerList
    plural: resourceservers
    shortNames:
    - a0api
    singular: resourceserver
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            nullable: false
            properties:
              id:
                nullable: true
                type: string
              lastConf:
                nullable: true
                properties:
                  id:
                    nullable: true
                    type: string
                  identifier:
                    nullable: true
                    type: string
                  name:
                    nullable: true
                    type: string
                  scopes:
                    items:
                      properties:
                        value:
                          nullable: true
                          type: string
                        description:
                          nullable: true
                          type: string
                      type: object
                    nullable: true
                    type: array
                  signing_alg:
                    enum:
                    - hs256
                    - rs256
                    - ps256
                    nullable: true
                    type: string
                  signing_secret:
                    nullable: true
                    type: string
                  token_lifetime:
                    format: int32
                    nullable: true
                    type: integer
                  token_lifetime_for_web:
                    format: int32
                    nullable: true
                    type: integer
                  allow_offline_access:
                    nullable: true
                    type: boolean
                  skip_consent_for_verifiable_first_party_clients:
                    nullable: true
                    type: boolean
                  verificationLocation:
                    nullable: true
                    type: string
                  token_dialect:
                    enum:
                    - AccessToken
                    - AccessTokenAuthZ
                    - Rfc9068Profile
                    - Rfc9068ProfileAuthz
                    nullable: true
                    type: string
                  enforce_policies:
                    nullable: true
                    type: boolean
                  consent_policy:
                    enum:
                    - TransactionalAuthorizationWithMfa
                    nullable: true
                    type: string
                  authorization_details:
                    items:
                      properties:
                        type:
                          nullable: true
                          type: string
                      type: object
                    nullable: true
                    type: array
                  token_encryption:
                    nullable: true
                    properties:
                      format:
                        enum:
                        - compact-nested-jwe
                        nullable: true
                        type: string
                      encryption_key:
                        nullable: true
                        properties:
                          name:
                            nullable: true
                            type: string
                          alg:
                            nullable: true
                            type: string
                          kid:
                            nullable: true
                            type: string
                          pem:
                            nullable: true
                            type: string
                        type: object
                    type: object
                  proof_of_possession:
                    nullable: true
                    properties:
                      required:
                        nullable: true
                        type: boolean
                      mechanism:
                        enum:
                        - mtls
                        nullable: false
                        type: string
                    type: object
                type: object
            type: object
          spec:
            nullable: false
            properties:
              tenantRef:
                nullable: true
                properties:
                  namespace:
                    nullable: true
                    type: string
                  name:
                    nullable: true
                    type: string
                required:
                - name
                type: object
              conf:
                nullable: true
                properties:
                  id:
                    nullable: true
                    type: string
                  identifier:
                    nullable: true
                    type: string
                  name:
                    nullable: true
                    type: string
                  scopes:
                    items:
                      properties:
                        value:
                          nullable: true
                          type: string
                        description:
                          nullable: true
                          type: string
                      type: object
                    nullable: true
                    type: array
                  signing_alg:
                    enum:
                    - hs256
                    - rs256
                    - ps256
                    nullable: true
                    type: string
                  signing_secret:
                    nullable: true
                    type: string
                  token_lifetime:
                    format: int32
                    nullable: true
                    type: integer
                  token_lifetime_for_web:
                    format: int32
                    nullable: true
                    type: integer
                  allow_offline_access:
                    nullable: true
                    type: boolean
                  skip_consent_for_verifiable_first_party_clients:
                    nullable: true
                    type: boolean
                  verificationLocation:
                    nullable: true
                    type: string
                  token_dialect:
                    enum:
                    - AccessToken
                    - AccessTokenAuthZ
                    - Rfc9068Profile
                    - Rfc9068ProfileAuthz
                    nullable: true
                    type: string
                  enforce_policies:
                    nullable: true
                    type: boolean
                  consent_policy:
                    enum:
                    - TransactionalAuthorizationWithMfa
                    nullable: true
                    type: string
                  authorization_details:
                    items:
                      properties:
                        type:
                          nullable: true
                          type: string
                      type: object
                    nullable: true
                    type: array
                  token_encryption:
                    nullable: true
                    properties:
                      format:
                        enum:
                        - compact-nested-jwe
                        nullable: true
                        type: string
                      encryption_key:
                        nullable: true
                        properties:
                          name:
                            nullable: true
                            type: string
                          alg:
                            nullable: true
                            type: string
                          kid:
                            nullable: true
                            type: string
                          pem:
                            nullable: true
                            type: string
                        type: object
                    type: object
                  proof_of_possession:
                    nullable: true
                    properties:
                      required:
                        nullable: true
                        type: boolean
                      mechanism:
                        enum:
                        - mtls
                        nullable: false
                        type: string
                    type: object
                type: object
            required:
            - tenantRef
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}