apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auth0-operator-role
  labels: {{- include "auth0-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - kubernetes.auth0.com
  resources:
  - tenants
  - clients
  - resourceservers
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - '*'
- apiGroups:
  - kubernetes.auth0.com
  resources:
  - clientgrants
  - connections
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - create
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
- apiGroups:
  - kubernetes.auth0.com
  resources:
  - tenants/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - kubernetes.auth0.com
  resources:
  - clients/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - kubernetes.auth0.com
  resources:
  - resourceservers/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - kubernetes.auth0.com
  resources:
  - clientgrants/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - kubernetes.auth0.com
  resources:
  - connections/status
  verbs:
  - get
  - update
  - patch