apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auth0-operator-binding
  labels: {{- include "auth0-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: auth0-operator-role
subjects:
  - kind: ServiceAccount
    name: auth0-operator
    namespace: {{ .Release.Namespace }}